name = "bikes-sync"
main = "worker.js"
compatibility_date = "2025-01-01"

# Created by: wrangler kv namespace create BIKES
# then paste the returned id below.
[[kv_namespaces]]
binding = "BIKES"
id = "5083f4b52861419fa138baa8dd05f856"
